VenusProtocol/vips

simulations/vip-121/abi/VBep20Abi.json, simulations/vip-121/simulations.ts, vips/vip-121.ts
transfer 90329999850000000000 (atoms) BTC (90,32999985 full BTC) from the treasury to the Normal timelock contract
repay 90.32999985 BTC debt on behalf of the account 0xef044206db68e40520bfa82d45419d498b4bc7bf from the Normal timelock contract
Resolves VEN-1529
=> [VEN-1529]: add simulation for vip-121

simulations/vip-122/abi/RateModelAbi.json, simulations/vip-122/abi/VBep20Abi.json, simulations/vip-122/abi/comptroller.json, simulations/vip-122/simulations.ts, vips/vip-122.ts
Given the significant shifts in crypto markets, Gauntlet’s platform has evaluated all assets on Venus's active markets and has
identified opportunities to adjust parameters for certain assets for the benefit of the protocol.
ETH & BTC
Changes:
base: 0.0 -> 0.0 | 0 -> 0
kink: 0.75 -> 0.75 | 750000000000000000 -> 750000000000000000
multiplier: 0.1267 -> 0.09 | 12052891933 -> 8561643835
jump multiplier: 2.0 -> 2.0 | 190258751902 -> 190258751902
LINK & LTC & MATIC & XRP
Changes:
base: 0.02 -> 0.02 | 1902587519 -> 1902587519
kink: 0.6 -> 0.6 | 600000000000000000 -> 600000000000000000
multiplier: 0.15 -> 0.12 | 14269406392 -> 11415525114
jump multiplier: 3.0 -> 3.0 | 285388127853 -> 285388127853
BNB
Changes:
base: 0 -> 0 | 0 -> 0
kink: 0.6 -> 0.6 | 600000000000000000 -> 600000000000000000 …
=> [VEN-1530] [VEN-1476]: vip-122 simulations - Gauntlet's risk parameters

simulations/vip-130/abi/RateModelAbi.json, simulations/vip-130/abi/VBep20Abi.json, simulations/vip-130/abi/comptroller.json, simulations/vip-130/simulations.ts, vips/vip-130.ts
XVS
Raise supply cap to 1,500,000 from 1,300,000
TRXOLD
Raise base multiplier to 1.0 from .15 (Raise borrow APR to ~100%)\
SXP
Raise base multiplier to .30 from .15 (Raise borrow APR to ~100%)
BETH
Decrease collateral factor to 0.50 from 0.60
Decrease borrow and supply cap to 0
WBETH
Raise borrow cap to 550 from 200
Raise supply cap to 800 from 300`,
Resolves VEN-1629
=> [VEN-1629]: add simulations for week 20th June Risk Parameters Update

simulations/vip-137/abi/IERC20UpgradableAbi.json, simulations/vip-137/simulations.ts, src/utils.ts, vips/vip-137.ts
This PR adds a VIP and a simulation for withdrawing the reserves for Q2 2023. It allocates 10% to the buyback and sends 90% to treasury for later allocation according to the tokenomics.
=> Reserves allocation, Q2 2023

simulations/vip-138/abi/IERC20UpgradableAbi.json, simulations/vip-138/simulations.ts, vips/vip-138.ts
If passed this VIP will perform the following actions:
● Transfer 18,000 USDC to Peckshield for the Diamond Comptroller audit
● Transfer 6,000 USDC to Peckshield for the Oracle upgrade audit
● Transfer 19,000 USDT to Certik for the retainer program
● Transfer 20,000 USDT to Fairyproof for the Automatic income allocation audit
● Transfer 277,200 USDC to OpenZeppelin for the security partnership`,
=> add simulations for vip-138 payment to auditors

simulations/vip-143/abi/comptroller.json, simulations/vip-143/simulations.ts, vips/vip-143.ts
Changes:
```
Supply cap of WBETH: 4,000 -> 8,000
Borrow cap of WBETH: 550 -> 1,100
```
Following Chaos Labs recommendations: https://community.venus.io/t/chaos-labs-supply-and-borrow-cap-recommendations-for-wbeth/3655
Resolves VEN-1722
=> [VEN-1722]: add VIP commands to update the caps of WBETH

simulations/vip-155/vip-155/abi/erc20.json, simulations/vip-155/vip-155/abi/rewardsDistributor.json, simulations/vip-155/vip-155/simulations.ts, vips/vip-155/vip-155.ts
This PR adds a simulation for configuring the second round of BSW rewards
=> [VEN-1731]: add a simulation for BSW rewards

simulations/vip-161/vip-161-testnet/abi/COMPTROLLER_ABI.json, simulations/vip-161/vip-161-testnet/abi/INTEREST_RATE_MODEL_ABI.json, simulations/vip-161/vip-161-testnet/abi/VBEP20_ABI.json, simulations/vip-161/vip-161-testnet/simulations.ts, simulations/vip-161/vip-161/abi/COMPTROLLER_ABI.json, simulations/vip-161/vip-161/abi/INTEREST_RATE_MODEL_ABI.json, simulations/vip-161/vip-161/abi/VBEP20_ABI.json, simulations/vip-161/vip-161/simulations.ts, vips/vip-161/vip-161-testnet.ts, vips/vip-161/vip-161.ts
**BUSD**
- Set supply caps in BUSD market to 0
- Set borrow caps in BUSD market to 1
- Set reserve factor in BUSD market to 100%
- Pause the following actions in the BUSD market: mint, borrow, enter markets
- Set XVS reward to 0 in BUSD market 
**TUSDOLD**
- Reduce jump multiplier in TUSDOLD market from 2.5 to 0.5
**ankrBNB DeFi**
- ncrease supply cap by 2X to 10,000 in ankrBNB market of DeFi pool
Resolves VEN-1868
=> [VEN-1868]: Risk Parameters Update

simulations/vip-171/abi/comptroller.json, simulations/vip-171/simulations.ts, vips/vip-171.ts
This VIP reduces XVS emissions by 75% for all markets in the core pool (except those where XVS rewards are disabled). VAI vault emission rate stays unchanged.
=> [VEN-1946]: add simulations for XVS emissions reduction

simulations/vip-173/abi/IERC20UpgradableAbi.json, simulations/vip-173/abi/VTreasury.json, simulations/vip-173/simulations.ts, src/utils.ts, src/vip-framework/index.ts, vips/vip-173.ts
This PR adds a simulation for "VIP-173 Payments Issuance for performed Audits". It also modifies callbackAfterExecution type a bit to simplify assertions, see commit msg for details.
=> [VEN-2001]: Payments to Peckshield and Code4Rena

simulations/vip-183/abi/IERC20UpgradableAbi.json, simulations/vip-183/simulations.ts, vips/vip-183.ts
This PR adds Q3 2023 funds allocation VIP along with the corresponding simulation.
The VIP does the following actions:
* transfers 10% of the core pool reserves (*) to the buyback wallet
* transfers 90% of the core pool reserves (*) to Venus Treasury
* transfers 22,793.63 USDT (10% of the core pool liquidations income in USDT) from treasury to the buyback wallet
* ~~transfers 10% of the total IL income from treasury to the buyback wallet~~
(*) BUSD, TUSDOLD reserves are not taken into account due to insufficient liquidity; XVS, CAN, LUNA, UST are excluded because of negligible amounts or deprecation.
=> [VEM-2029]: add funds allocation VIP (Q3 2023)

multisig/proposals/vip-002/vip-002-ethereum-bootstrap-liquidity.ts, multisig/simulations/vip-002/vip-002-ethereum-bootstrap-liquidity/abis/ERC20.json, multisig/simulations/vip-002/vip-002-ethereum-bootstrap-liquidity/simulations.ts
Resolves VEN-2320
We need WBTC tokens, not BBTC. We'll swap the BBTC tokens for WBTC using Uniswap, and send them to the VTreasuryV8 contract
Related to https://github.com/VenusProtocol/vips/pull/162
=> [VEN-2325]: swap 0.3 BBTC for WBTC

src/networkAddresses.ts, src/vip-framework/checks/checkCorePoolComptroller.ts
This PR:
* changes the address of `GENERIC_TEST_USER_ACCOUNT` on bscmainnet to the one that has ETH, USDT, and XVS
* fixes a logic bug in the balances check
=> fix: logic and addresses in generic tests framework

.gitignore, README.md, scripts/createProposal.ts, src/transactions.ts
Currently the proposal hard hat commands don't support the current repo structure of organizing proposals in directories. This PR updates to support arbitrary file paths and function names. 
When running the hardhat commands instead of declaring the proposal number you pass the path. It also requires the proposal creation function to be the default export which decouples the name of the function from consumers of the function
Resolves VEN
=> feat: add support for arbitrary vip paths

simulations/vip-274/abi/IERC20UpgradableAbi.json, simulations/vip-274/abi/binanceOracle.json, simulations/vip-274/abi/resilientOracle.json, simulations/vip-274/bscmainnet.ts, vips/vip-274/bscmainnet.ts
AGEUR has recently changed its token symbol to EURA, which has broken BOracle price feed. This PR adds a symbol override so that the price feed is live again.
=> fix: add symbol override for agEUR

package.json, simulations/vip-285/abi/IERC20UpgradableAbi.json, simulations/vip-285/abi/NonfungiblePositionManager.json, simulations/vip-285/abi/VTreasury.json, simulations/vip-285/bscmainnet.ts, vips/vip-285/bscmainnet.ts, yarn.lock
This VIP redeems PCS v2 LP tokens from the v2 pool and deposits the received USDT/VAI to a PCS v3 pool. The range is 500 ticks concentrated somewhere between [0.966, 1.036] depending on the current spot price.
* The lowest possible range is if the spot price is 0.990 USDT/VAI, it's equal to [0.966, 1.015]
* The highest possible range is if the spot price is 1.010 USDT/VAI, it's equal to [0.985, 1.035]
* If the spot price is lower than 0.990 USDT/VAI or higher than 1.010 USDT/VAI, the transaction will revert
Although the proposed approach is a bit non-deterministic in terms of the resulting range, it allows for maximizing the supplied amount since the tokens are added proportionally and no excess of a single token is required.
The temporary contract that does the operation is at …
=> [VEN-2370]: move VAI/USDT liquidity from PCS v2 to PCS v3

simulations/vip-301/abi/Comptroller.json, simulations/vip-301/abi/ERC20.json, simulations/vip-301/abi/VAIController.json, simulations/vip-301/bscmainnet.ts, vips/vip-301/bscmainnet.ts
This VIP repays bad debt of VAI borrowers. It uses a new version of the governance utility contract that supports batch VAI repayments on behalf of another user, which, in turn, depends on the VAIController upgrade defined here: https://github.com/VenusProtocol/vips/pull/259
=> [VEN-2549]: Add simulations for VAI debt repayment

multisig/proposals/arbitrumsepolia/vip-011/index.ts, multisig/simulations/arbitrumsepolia/vip-011/abi/ProtocolShareReserve.json, multisig/simulations/arbitrumsepolia/vip-011/index.ts
This VIP includes command to set right `PoolRegistry` address in `PSR` contract on **ArbitrumSepolia**.
**Reason for creation of this VIP:**
The `PoolRegistry` address set in `PSR` is the old address which was deployed on solidity version `0.8.19` and was redeployed with `0.8.25` solidity version. Due to which `PSR` held the old `PoolRegistry` address.
=> Vip to set correct PoolRegistry address on PSR

multisig/proposals/ethereum/vip-042/index.ts, multisig/simulations/ethereum/vip-042/abi/Comptroller.json, multisig/simulations/ethereum/vip-042/abi/RewardsDistributor.json, multisig/simulations/ethereum/vip-042/abi/XVS.json, multisig/simulations/ethereum/vip-042/index.ts, vips/vip-335/bscmainnet.ts
This VIP/multisig tx resumes market incentives on Ethereum. The incentives were stopped at block #20210819 despite the community vote to gradually decrease the emissions. This PR introduces new rewards distributor contracts that would continue rewarding users with XVS for supplying/borrowing on WETH, WBTC, USDT, USDC, crvUSD, TUSD, CRV, wstETH.
=> feat: VIP-335 [Ethereum] Resume Market Incentives

multisig/proposals/zksyncsepolia/vip-002/index.ts, multisig/simulations/zksyncsepolia/vip-002/abi/xvs.json, multisig/simulations/zksyncsepolia/vip-002/abi/xvsBridgeAdmin.json, multisig/simulations/zksyncsepolia/vip-002/abi/xvsProxyOFTDest.json, multisig/simulations/zksyncsepolia/vip-002/index.ts
=> [VEN-2682]: Vip for XVS bridge for zksyncsepolia

multisig/proposals/arbitrumone/vip-010/index.ts, multisig/proposals/ethereum/vip-055/index.ts, multisig/simulations/arbitrumone/vip-010/abi/VTokenIL.json, multisig/simulations/arbitrumone/vip-010/index.ts, multisig/simulations/ethereum/vip-055/abi/VTokenIL.json, multisig/simulations/ethereum/vip-055/index.ts, simulations/vip-354/abi/VTokenCorePool.json, simulations/vip-354/abi/VTokenIL.json, simulations/vip-354/bscmainnet.ts, vips/vip-354/bscmainnet.ts
https://community.venus.io/t/chaos-labs-interest-rate-curve-amendment-for-stablecoins-on-venus/4531
Note: Contrary to what's written in the proposal, the multiplier for crvUSD_Core on Ethereum is currently set to 0.0875, not 0.1250
=> [VEN-2759]: Chaos Labs recommendations (Aug, 15, 2024)

multisig/proposals/zksyncmainnet/vip-005/index.ts, multisig/simulations/zksyncmainnet/vip-005/abi/NativeTokenGateway.json, multisig/simulations/zksyncmainnet/vip-005/index.ts
=> [VEN-2745]:  VIP for NTG on Zksync mainnet

multisig/proposals/zksyncmainnet/vip-012/index.ts, multisig/simulations/zksyncmainnet/vip-012/abi/xvsProxyOFTDest.json, multisig/simulations/zksyncmainnet/vip-012/index.ts, simulations/vip-376/bscmainnet.ts, vips/vip-376/bscmainnet.ts
Resolves VEN-2849
Related to https://github.com/VenusProtocol/vips/pull/394, where the limits were configured for zkSync and the rest of the networks
=> [VEN-2849]: increase XVS bridge limits for BNB Chain/zkSync on the zkSync side

multisig/proposals/ethereum/vip-071/index.ts, multisig/simulations/ethereum/vip-071/abi/erc20.json, multisig/simulations/ethereum/vip-071/index.ts, simulations/vip-402/abi/OmnichainProposalSender.json, simulations/vip-402/abi/PoolRegistry.json, simulations/vip-402/abi/ResilientOracle.json, simulations/vip-402/abi/SingleTokenConverter.json, simulations/vip-402/abi/comptroller.json, simulations/vip-402/abi/vToken.json, simulations/vip-402/abi/weth.json, simulations/vip-402/bscmainnet.ts, simulations/vip-402/bsctestnet.ts, simulations/vip-402/ethereum.ts, simulations/vip-402/sepolia.ts, src/utils.ts, src/vip-framework/checks/checkIsolatedPoolsComptrollers.ts, vips/vip-402/bscmainnet.ts, vips/vip-402/bsctestnet.ts
This PR adds simulations for enabling LBTC market on Ethereum Core pool
=> [VEN-2940]: Add simulations for LBTC support

.github/workflows/ci.yml, simulations/vip-486/abi/Comptroller.json, simulations/vip-486/abi/JumpRateModel.json, simulations/vip-486/abi/JumpRateModelV2.json, simulations/vip-486/abi/PoolRegistry.json, simulations/vip-486/abi/VToken.json, simulations/vip-486/bscmainnet.ts, simulations/vip-486/bsctestnet.ts, simulations/vip-486/common.ts, tsconfig.json, vips/vip-486/bscmainnet.ts, vips/vip-486/bsctestnet.ts
This VIP enables the checkpoint interest rate models deployed in https://github.com/VenusProtocol/isolated-pools/pull/509 and https://github.com/VenusProtocol/venus-protocol/pull/587
=> [VEN-3163]: VIP to enable checkpoint rate models on BNB chain
