VenusProtocol/vips

simulations/vip-105/abi/IERC20UpgradableAbi.json
simulations/vip-105/simulations.ts
src/vip-framework/index.ts
tsconfig.json
vips/vip-105.ts

This PR adds simulations for reserves withdrawal, snapshotted at block #26956109 (2023-04-01 00:00 UTC)

VIP-105 simulations

---

src/transactions.ts

Because the data in env is in string format, this PR merely changes the datatype of the function parameters.

chore: update datatype of the function params

---

simulations/vip-113/abi/xvsVault.json
simulations/vip-113/abi/xvsVaultProxy.json
simulations/vip-113/simulations.ts
vips/vip-113.ts

This VIP accepts admin rights over the XVSVault and sets the new XVS reward speed.

test: simulate VIP-113 to set new vault reward speed

---

simulations/vip-116/abi/comptroller.json
simulations/vip-116/simulations.ts
vips/vip-116.ts

TRX:
Increase CF to 0.525 from 0.50
SXP:
Decrease CF to 0.0 from 0.125
XVS:
Increase supply cap to 1.5m from 1m
Increase CF to 0.60 from 0.55
Resolves VEN-1148

[VEN-1448]: add simulations for week May 8th Gauntlet recommendations

---

simulations/vip-125/abi/comptroller.json
simulations/vip-125/simulations.ts
vips/vip-125.ts

XVS:
>Increase supply cap to 1.3m from 1m
Resolves VEN-1575

[VEN-1575]: add vip-125 simulations

---

simulations/vip-140/vip-140-testnet/abi/comptroller.json
simulations/vip-140/vip-140-testnet/abi/erc20.json
simulations/vip-140/vip-140-testnet/abi/rewardsDistributor.json
simulations/vip-140/vip-140-testnet/simulations.ts
simulations/vip-140/vip-140/abi/comptroller.json
simulations/vip-140/vip-140/abi/erc20.json
simulations/vip-140/vip-140/abi/rewardsDistributor.json
simulations/vip-140/vip-140/simulations.ts
vips/vip-140/vip-140-testnet.ts
vips/vip-140/vip-140.ts

This PR adds a VIP enabling rewards for IL markets

[VEN-1687]: add rewards distributors to IL

---

simulations/vip-144/abi/IERC20UpgradableAbi.json
simulations/vip-144/abi/xvsVault.json
simulations/vip-144/simulations.ts
vips/vip-144.ts

Resolves VEN-1744
* Set XVS daily distribution in the XVSVault: 1780 XVS/day
* Transfer 9,216 USDT to the Community wallet

[VEN-1744]: add simulation for setting XVS rewards in the XVSVault

---

simulations/vip-147/abi/comptroller.json
simulations/vip-147/simulations.ts
vips/vip-147.ts

**FLOKI (GameFi pool):**
- Supply cap: 22,000,000,000 -> 44,000,000,000
Resolves VEN-1778

[VEN-1778]: Chaos labs recommendations for week July 24th, 2023

---

simulations/vip-148/abi/IERC20UpgradableAbi.json
simulations/vip-148/simulations.ts
vips/vip-148.ts

Quantstamp	Liquidator	July/12th - July/24th	Done	$10,000
Quantstamp	PSM	July/26th - July/28th	Not started	$10,000
Quantstamp	Diamond Comptroller	August/7th - August/16th	Not started	$30,000
Peckshield	Automatic allocation of income	July/28th - August/7th	Not started	$18,000
Peckshield	Venus Prime	August/9th - August/17th	Not started	$16,800
Fairyproof	Venus Prime	July/28th - August/4th	Not started	$12,500
Certik	Retainer program	August 2023	-	$19,000`,
Resolves VEN-1769

[VEN-1769]: payments to auditor

---

simulations/vip-158/abi/comptroller.json
simulations/vip-158/simulations.ts
vips/vip-158.ts

This PR proposes a VIP to change risk parameters, taking in mind Chaos labs recommendations:
market: TUSD (core pool)
new supply cap: 1,500,000
new borrow cap: 1,200,000
Resolves VEN-1822

[VEN-1822]: Chaos labs recommendations for week August 14th, 2023

---

scripts/proposeTestnetVIP.ts
simulations/vip-177/abi/IERC20UpgradableAbi.json
simulations/vip-177/abi/VTreasury.json
simulations/vip-177/vip-177-testnet/abi/comptroller.json
simulations/vip-177/vip-177-testnet/abi/erc20.json
simulations/vip-177/vip-177-testnet/abi/poolRegistry.json
simulations/vip-177/vip-177-testnet/abi/rateModel.json
simulations/vip-177/vip-177-testnet/abi/rewardsDistributor.json
simulations/vip-177/vip-177-testnet/abi/vToken.json
simulations/vip-177/vip-177-testnet/simulations.ts
simulations/vip-177/vip-177/abi/comptroller.json
simulations/vip-177/vip-177/abi/erc20.json
simulations/vip-177/vip-177/abi/poolRegistry.json
simulations/vip-177/vip-177/abi/rateModel.json
simulations/vip-177/vip-177/abi/rewardsDistributor.json
simulations/vip-177/vip-177/abi/vToken.json
simulations/vip-177/vip-177/simulations.ts
vips/vip-177/vip-177-testnet.ts
vips/vip-177/vip-177.ts

[VEN-1997]: add SnBNB market to Liquid Staked BNB pool

---

simulations/vip-188/abi/IAccessControlManager_ABI.json
simulations/vip-188/abi/xvsVault.json
simulations/vip-188/simulations.ts
vips/vip-188.ts

[VEN-2088]: add VIP to adjust the APR in the XVSVault for Q4 2023

---

README.md
multisig/helpers/utils.ts
scripts/createProposal.ts
scripts/executeMultiSigTx.ts

This PR adds an option to `createProposal` script to export a multisig tx into a Gnosis Safe JSON format.
Note: 
This PR should be merged after the [Sepolia VIP Multisig Execution PR](https://github.com/VenusProtocol/vips/pull/64) as it contains a small refactoring and all the commits from the PR mentined.
The last 3 commits starting from
[3fe2655](https://github.com/VenusProtocol/vips/pull/81/commits/3fe26555a0b35f336c301b87d7f532439b6fd797)
contain the changes of this PR
Resolves VEN-1896

[VEN-1896]: export proposal into gnosis safe format

---

simulations/vip-212/abi/IERC20UpgradableAbi.json
simulations/vip-212/abi/VTreasuryAbi.json
simulations/vip-212/simulations.ts
vips/vip-212.ts

[VEN-2190]: vip to issue payments for audits

---

multisig/proposals/vip-006/vip-006-sepolia.ts
multisig/simulations/vip-006/vip-006-sepolia/simulations.ts

[VEN-2216]: Configure rewards on sepolia

---

simulations/vip-213/abi/comptroller.json
simulations/vip-213/simulations.ts
vips/vip-213.ts

- **MATIC** (Core pool)
- Increase supply cap to 16,000,000 (from 8,000,000)
- **PLANET** (Defi pool)
- Increase supply cap to 4,000,000,000 (from 2,000,000,000)
- Increase borrow cap to 1,500,000,000 (from 1,000,000,000)
Resolves VEN-2228

[VEN-2228]: Chaos labs recommendations for the week October 6th, 2023

---

simulations/vip-214/abi/IERC20UpgradableAbi.json
simulations/vip-214/abi/VTreasuryAbi.json
simulations/vip-214/simulations.ts
vips/vip-214.ts

[VEN-2230]

---

simulations/vip-215/abi/IERC20UpgradableAbi.json
simulations/vip-215/abi/VBep20Abi.json
simulations/vip-215/abi/VBep20DelegateAbi.json
simulations/vip-215/abi/comptroller.json
simulations/vip-215/abi/moveDebtDelegate.json
simulations/vip-215/abi/priceOracleAbi.json
simulations/vip-215/simulations.ts
src/vip-framework/index.ts
vips/vip-215.ts

If passed this VIP will perform the following actions:
* Authorize the MoveDebtDelegate contract, to borrow USDT or USDC on behalf of the account [0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc](https://bscscan.com/address/0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc)
* Accept the ownership of the MoveDebtDelegate ([Governance](https://bscscan.com/address/0x939bD8d64c0A9583A7Dcea9933f7b21697ab6396) will be the owner of this contract)

[VEN-2227]: VIP-215 BUSD debt mitigation

---

.env.example
multisig/proposals/vip-001/vip-001-opbnbtestnet.ts
multisig/simulations/vip-001/vip-001-opbnbtestnet/abi/binanceOracle.json
multisig/simulations/vip-001/vip-001-opbnbtestnet/abi/boundValidator.json
multisig/simulations/vip-001/vip-001-opbnbtestnet/abi/proxyAdmin.json
multisig/simulations/vip-001/vip-001-opbnbtestnet/abi/resilientOracle.json
multisig/simulations/vip-001/vip-001-opbnbtestnet/simulations.ts
src/networkAddresses.ts

[VEN-2203]: Simulations for oracle configuration on opBNB Testnet

---

simulations/vip-221/vip-221-testnet/abi/Comproller_ABI.json
simulations/vip-221/vip-221-testnet/simulations.ts
simulations/vip-221/vip-221/abi/Comproller_ABI.json
simulations/vip-221/vip-221/simulations.ts
vips/vip-221/vip-221-testnet.ts
vips/vip-221/vip-221.ts

[VEN-2260]: Chaos labs recommendations for the week December 19th, 2023 - BUSD CF to 0.3 and XVS supply cap to 1.75M

---

simulations/vip-223/vip-223-testnet/abi/Comproller_ABI.json
simulations/vip-223/vip-223-testnet/simulations.ts
simulations/vip-223/vip-223/abi/Comproller_ABI.json
simulations/vip-223/vip-223/simulations.ts
vips/vip-223/vip-223-testnet.ts
vips/vip-223/vip-223.ts

This VIP sets BUSD collateral factor to 0, preparing for the deprecation of BUSD price feed

[VEN-2270]: set BUSD CF to 0

---

multisig/proposals/vip-003/vip-003-ethereum.ts
multisig/simulations/vip-003/vip-003-ethereum/abi/resilientOracle.json
multisig/simulations/vip-003/vip-003-ethereum/abi/xvs.json
multisig/simulations/vip-003/vip-003-ethereum/abi/xvsBridgeAdmin.json
multisig/simulations/vip-003/vip-003-ethereum/abi/xvsProxyOFTDest.json
multisig/simulations/vip-003/vip-003-ethereum/simulations.ts

[VEN-2188]: XVS token bridge configurations multisig proposal for Ethereum

---

simulations/vip-234/abi/xvsVault.json
simulations/vip-234/simulations.ts
vips/vip-234.ts

Resolves VEN-2294
Set the XVSVault distribution speed to ~~1,640~~ 1,630 XVS/day

[VEN-2294]: add VIP to set APR of the XVSVault for Q1 2024

---

multisig/proposals/vip-003/vip-003-sepolia-2.ts
multisig/simulations/vip-003/vip-003-sepolia-2/abi/xvs.json
multisig/simulations/vip-003/vip-003-sepolia-2/abi/xvsProxyOFTDest.json
multisig/simulations/vip-003/vip-003-sepolia-2/simulations.ts
simulations/vip-232/vip-232-testnet-2/abi/XVSProxyOFTSrc.json
simulations/vip-232/vip-232-testnet-2/simulations.ts
vips/vip-232/vip-232-testnet-2.ts

1. MaxSingleTransactionLimit : 10,000
2. MaxDailyLimit 50,000
3. MaxSingleReceiveTransactionLimit : 10,000
4. MaxDailyReceiveLimit : 50,000
5. XVS_PROXY_OFT_DEST : 500,000
Resolves VEN-2303

[VEN-2303]: increase single and daily transaction limits in xvs bridge and mint cap limits in xvs token

---

simulations/vip-237/abi/ERC20.json
simulations/vip-237/abi/VTreasury.json
simulations/vip-237/simulations.ts
vips/vip-237.ts

Resolves VEN-2306
- send 296,719 DAI to [Binance](https://bscscan.com/address/0x6657911F7411765979Da0794840D671Be55bA273) ($296,719 approximately)
The tokens will be converted to USDC and sent back to the treasury, where they will be partially used to fund the Prime program

[VEN-2306]: treasury management

---

multisig/proposals/vip-005/vip-005-opbnbtestnet.ts
multisig/simulations/vip-005/vip-005-opbnbtestnet/abi/accessControlManager.json
multisig/simulations/vip-005/vip-005-opbnbtestnet/abi/protocolShareReserve.json
multisig/simulations/vip-005/vip-005-opbnbtestnet/abi/vToken.json
multisig/simulations/vip-005/vip-005-opbnbtestnet/simulations.ts

[VEN-2311]: PSR configuration on opBNB Testnet

---

simulations/vip-235/abi/ComptrollerAbi.json
simulations/vip-235/simulations.ts
vips/vip-235.ts

[VEN-2288]: chaos lab recommendation for the week January 8th, 2024: part 1

---

multisig/proposals/vip-009/vip-009-sepolia.ts
multisig/simulations/vip-009/vip-009-sepolia/abi/resilientOracle.json
multisig/simulations/vip-009/vip-009-sepolia/abi/wstETH.json
multisig/simulations/vip-009/vip-009-sepolia/simulations.ts

multisig VIP for configuration and simulation of the new wstETH oracle
Resolves VEN-2315

[VEN-2315]: VIP and simulation for configuring wstETH oracle

---

multisig/proposals/vip-010/vip-010-sepolia.ts
multisig/simulations/vip-010/vip-010-sepolia/abi/comptroller.json
multisig/simulations/vip-010/vip-010-sepolia/abi/erc20.json
multisig/simulations/vip-010/vip-010-sepolia/abi/poolRegistry.json
multisig/simulations/vip-010/vip-010-sepolia/abi/vToken.json
multisig/simulations/vip-010/vip-010-sepolia/simulations.ts

[VEN-2315]: VIP to configure Liquid Staked ETH Pool to Sepolia

---

simulations/vip-244/abi/IERC20UpgradableAbi.json
simulations/vip-244/abi/ProxyAdmin.json
simulations/vip-244/abi/VBep20DelegateAbi.json
simulations/vip-244/abi/comptroller.json
simulations/vip-244/abi/moveDebtDelegate.json
simulations/vip-244/simulations.ts
vips/vip-244.ts

This PR adds a simulation for a VIP to move the most significant bad debt from the current debtors to the [BNB bridge exploiter account](https://bscscan.com/address/0x489a8756c18c0b8b24ec2a2b9ff3d4d447f79bec).

[VEN-2338] VIP-244 Move Bad Debt

---

simulations/vip-246/abi/VAIController_ABI.json
simulations/vip-246/bscmainnet.ts
simulations/vip-246/bsctestnet.ts
vips/vip-246/bscmainnet.ts
vips/vip-246/bsctestnet.ts

Add VIP and simulations for VAI base and float rate updates per steakhouse recomendations
Resolves VEN-2334

[VEN-2334]: add vip for steakhouse vai recomendations

---

multisig/proposals/vip-009/vip-009-ethereum.ts
multisig/simulations/vip-009/vip-009-ethereum/abi/resilientOracle.json
multisig/simulations/vip-009/vip-009-ethereum/abi/wstETH.json
multisig/simulations/vip-009/vip-009-ethereum/simulations.ts

[VEN-2317]: configure wstETH oracle on Ethereum

---

simulations/vip-261/abi/DiamondConsolidated.json
simulations/vip-261/bscmainnet.ts
simulations/vip-261/bsctestnet.ts
vips/vip-261/bscmainnet.ts
vips/vip-261/bsctestnet.ts

Adds VIP per Chaos Labs recommendations to increase the WBETH borrow cap to 4000

[VEN-2413]: vip to increase wbeth borrow cap to 4000

---

multisig/proposals/vip-011/vip-011-opbnbmainnet.ts
multisig/simulations/vip-011/vip-011-opbnbmainnet/abi/vToken.json
multisig/simulations/vip-011/vip-011-opbnbmainnet/simulations.ts

[VEN-2422]: update jump rate of WBNB to 300% on opBNB

---

simulations/vip-264/abi/ILInterestRateModelABI.json
simulations/vip-264/abi/RateModelAbi.json
simulations/vip-264/abi/VBep20DelegatorAbi.json
simulations/vip-264/simulations.ts
vips/vip-264.ts
vips/vip-264/bscmainnet.ts

This PR introduces a VIP and Simulation for changing IR curve for vBNB core pool on bscmainnet.
Resolves VEN-2426

[VEN-2426]Change IR curve for vBNB core pool on bscmainnet

---

simulations/vip-267/abi/IERC20UpgradableAbi.json
simulations/vip-267/abi/RewardFacet.json
simulations/vip-267/abi/VTreasury.json
simulations/vip-267/abi/XVSProxyOFTSrc.json
simulations/vip-267/simulations.ts
vips/vip-267/bscmainnet.ts

[VEN-2447]: Fund the XVSVestingProxy with XVS from the Treasury and bridge XVS to Ethereum

---

multisig/proposals/vip-015/vip-015-ethereum.ts
multisig/simulations/vip-015/vip-015-ethereum/abi/XVS.json
multisig/simulations/vip-015/vip-015-ethereum/simulations.ts

[VEN-2485] Transfer XVS to Community Wallet

---

simulations/vip-299/abi/ERC20.json
simulations/vip-299/abi/Liquidator.json
simulations/vip-299/abi/VAIController.json
simulations/vip-299/bscmainnet.ts
simulations/vip-299/bsctestnet.ts
vips/vip-299/bscmainnet.ts
vips/vip-299/bsctestnet.ts

This PR adds simulations for VAIController upgrade implemented in https://github.com/VenusProtocol/venus-protocol/pull/467

[VEN-2525]: add simulations for VAIController upgrade

---

simulations/vip-300/abi/ComptrollerAbi.json
simulations/vip-300/bscmainnet.ts
vips/vip-300/bscmainnet.ts

[VEN-2591]: Chaos lab recommendation (May 1st, 2024)

---

simulations/vip-313/abi/ERC20.json
simulations/vip-313/abi/VTreasury.json
simulations/vip-313/bscmainnet.ts
vips/vip-313/bscmainnet.ts

[VEN-2619]: VIP to transfer funds to Gitcoin for the grants

---

multisig/proposals/ethereum/vip-032/index.ts
multisig/simulations/ethereum/vip-032/abi/ILComprollerAbi.json
multisig/simulations/ethereum/vip-032/index.ts
simulations/vip-315/simulations.ts
vips/vip-315/bscmainnet.ts

Includes VIP on BNB mainnet proposing the update and multisig on ethereum to update the vweETH adn vstETH markets per Chaos' Labs reccomendations

[VEN-2620]: add vip and multisig to update risk params per Chaos labs 5/27/24 recommendations

---

simulations/vip-321/abi/ERC20.json
simulations/vip-321/abi/VTreasuryAbi.json
simulations/vip-321/bscmainnet.ts
vips/vip-321/bscmainnet.ts

Fund dev wallet with 18000 USDC to pay for migrating the subgraphs to The Graph's decentralized network.
Resolves VEN-2628

[VEN-2628] feat: create VIP to send funds to the dev wallet to fund subgraphs

---

simulations/vip-334/abi/ERC20.json
simulations/vip-334/bscmainnet.ts
vips/vip-334/bscmainnet.ts

Proposal to transfers tokens from the treasury to the community wallet where they will be bridged and used to fund prime boosted rewards

feat: add vip-334 to fund prime boost

---

multisig/proposals/ethereum/vip-043/index.ts
multisig/proposals/sepolia/vip-041/index.ts
multisig/simulations/ethereum/vip-043/abi/ILComprollerAbi.json
multisig/simulations/ethereum/vip-043/abi/beacon.json
multisig/simulations/ethereum/vip-043/index.ts
multisig/simulations/sepolia/vip-041/abi/ILComptroller.json
multisig/simulations/sepolia/vip-041/index.ts
vips/vip-336/bscmainnet.ts

Proposal to upgrade Controller with increased max collateral factor to 95%
Set Chaos Labs recommendations

feat: add proposal set chaos labs recommendations and upgrade controller

---

multisig/proposals/ethereum/vip-044/index.ts
multisig/simulations/ethereum/vip-044/abi/erc20.json
multisig/simulations/ethereum/vip-044/index.ts
simulations/vip-337/abi/PrimeLiquidityProvider.json
simulations/vip-337/abi/ProtocolShareReserve.json
simulations/vip-337/bscmainnet.ts
vips/vip-337/bscmainnet.ts

Updates Prime Reward Parameters
Transfers tokens accidentally sent to Prime Liquidity Provider back to sender

feat: add vip adjusting prime reward parameters

---

simulations/vip-338/abi/PrimeLiquidityProvider.json
simulations/vip-338/bscmainnet.ts
vips/vip-338/bscmainnet.ts

Fix reward  speeds by hardcoding them

VIP-338 correction of prime speeds

---

simulations/vip-364/abi/comptroller.json
simulations/vip-364/bscmainnet.ts
vips/vip-364/bscmainnet.ts

[VEN-2799]: Update XVS emissions on BNB chain

---

multisig/proposals/zksyncmainnet/vip-013/index.ts
multisig/simulations/zksyncmainnet/vip-013/abi/Comptroller.json
multisig/simulations/zksyncmainnet/vip-013/index.ts
vips/vip-379/bscmainnet.ts

[VEN-2855]: add TX to increase caps on zkSync

---

hardhat.config.zksync.ts
scripts/createProposal.ts
src/transactions.ts

[VEN-2852]: createProposal task in zksync config

---

multisig/proposals/ethereum/vip-067/index.ts
multisig/simulations/ethereum/vip-067/abi/SingleTokenConverter.json
multisig/simulations/ethereum/vip-067/index.ts
src/utils.ts
src/vip-framework/index.ts
vips/vip-389/bscmainnet.ts

Add VIP for Ethereum token converter incentives

[VEN-2753]: Ethereum token converter incentives

---

multisig/proposals/zksyncmainnet/vip-015/index.ts
multisig/proposals/zksyncsepolia/vip-012/index.ts
multisig/simulations/zksyncmainnet/vip-015/abi/comptroller.json
multisig/simulations/zksyncmainnet/vip-015/abi/erc20.json
multisig/simulations/zksyncmainnet/vip-015/abi/rateModel.json
multisig/simulations/zksyncmainnet/vip-015/abi/resilientOracle.json
multisig/simulations/zksyncmainnet/vip-015/abi/vToken.json
multisig/simulations/zksyncmainnet/vip-015/index.ts
multisig/simulations/zksyncsepolia/vip-012/abi/comptroller.json
multisig/simulations/zksyncsepolia/vip-012/abi/erc20.json
multisig/simulations/zksyncsepolia/vip-012/abi/rateModel.json
multisig/simulations/zksyncsepolia/vip-012/abi/vToken.json
multisig/simulations/zksyncsepolia/vip-012/index.ts
simulations/vip-392/abi/ERC20.json
simulations/vip-392/abi/VtreasuryAbi.json
simulations/vip-392/bscmainnet.ts
vips/vip-392/bscmainnet.ts

[VEN-2925]: add USDC market on zksync

---

simulations/vip-397/abi/comptroller.json
simulations/vip-397/abi/resilientOracle.json
simulations/vip-397/bscmainnet.ts
vips/vip-397/bscmainnet.ts

Update BNBx oracle and unpause LST BNB pool markets

[VEN-2933]: update BNBx oracle and reenable the markets

---

simulations/vip-398/abi/CoreComptroller.json
simulations/vip-398/bscmainnet.ts
vips/vip-398/bscmainnet.ts

Source: https://community.venus.io/t/chaos-labs-risk-parameter-updates-11-05-24/4708

[VEN-2936]: VIP to increase supply cap of SolvBTC

---

simulations/vip-416/abi/CoreComptroller.json
simulations/vip-416/bscmainnet.ts
vips/vip-416/bscmainnet.ts

Resolves VEN-2980
See https://community.venus.io/t/chaos-labs-risk-parameter-updates-12-31-2024/4806

[VEN-2980]: increase caps of SolvBTC

---

simulations/vip-417/abi/Comptroller.json
simulations/vip-417/abi/OmnichainProposalSender.json
simulations/vip-417/bscmainnet.ts
simulations/vip-417/zksyncmainnet.ts
vips/vip-417/bscmainnet.ts

Resolves VEN-2988
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-5-2025/4811?u=chaoslabs

[VEN-2988]: add recommendations to increase caps on ZKSync

---

simulations/vip-418/abi/Comptroller.json
simulations/vip-418/abi/OmnichainProposalSender.json
simulations/vip-418/bscmainnet.ts
simulations/vip-418/zksyncmainnet.ts
vips/vip-418/bscmainnet.ts

Resolves VEN-2996
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-6-2025/4815

[VEN-2996]: add VIP to increase supply caps on ZK and USDC.e, and CF/LT on ZK

---

src/utils.ts
src/vip-framework/index.ts

[VEN-2977]: Check for correct target address in proposal on all chains

---

simulations/vip-420/abi/Comptroller.json
simulations/vip-420/abi/OmnichainProposalSender.json
simulations/vip-420/bscmainnet.ts
simulations/vip-420/zksyncmainnet.ts
vips/vip-420/bscmainnet.ts

Resolves VEN-3004
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-8-25/4819

[VEN-3004]: add VIP 420 to increase some caps on ZKsync

---

simulations/vip-423/abi/CoreComptroller.json
simulations/vip-423/abi/ILComptroller.json
simulations/vip-423/abi/OmnichainProposalSender.json
simulations/vip-423/bscmainnet.ts
simulations/vip-423/zksyncmainnet.ts
vips/vip-423/bscmainnet.ts

Resolves VEN-3011
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-11-25/4829

[VEN-3011]: add VIP 423 to adjust some risk parameters

---

simulations/vip-425/abi/Comptroller.json
simulations/vip-425/abi/OmnichainProposalSender.json
simulations/vip-425/bscmainnet.ts
simulations/vip-425/zksyncmainnet.ts
vips/vip-425/bscmainnet.ts

Resolves VEN-3020
https://community.venus.io/t/chaos-labs-risk-parameter-update-1-17-25/4834

[VEN-3020]: Chaos labs recommendations to increase some caps

---

simulations/vip-426/abi/Comptroller.json
simulations/vip-426/abi/OmnichainProposalSender.json
simulations/vip-426/bscmainnet.ts
simulations/vip-426/zksyncmainnet.ts
vips/vip-426/bscmainnet.ts

Resolves VEN-3021
https://community.venus.io/t/chaos-labs-risk-parameter-update-1-19-25/4836

[VEN-3021]: add VIP to adjust caps of USDC on ZKsync

---

simulations/vip-428/abi/Comptroller.json
simulations/vip-428/abi/OmnichainProposalSender.json
simulations/vip-428/bscmainnet.ts
simulations/vip-428/zksyncmainnet.ts
vips/vip-428/bscmainnet.ts

Resolves VEN-3023
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-21-25/4838

[VEN-3023]: add VIP to adjust caps of USDC, WBTC and ZK on ZKsync

---

simulations/vip-431/abi/CoreComptroller.json
simulations/vip-431/abi/ILComptroller.json
simulations/vip-431/abi/OmnichainProposalSender.json
simulations/vip-431/bscmainnet.ts
simulations/vip-431/zksyncmainnet.ts
vips/vip-431/bscmainnet.ts

Resolves VEN-3028
https://community.venus.io/t/chaos-labs-risk-parameter-updates-1-23-25/4840

[VEN-3028]: increase UNI (BNB Chain) and WBTC (ZKsync) caps

---

simulations/vip-441/abi/CoreComptroller.json
simulations/vip-441/bscmainnet.ts
vips/vip-441/bscmainnet.ts

Resolves VEN-3047
https://community.venus.io/t/chaos-labs-risk-parameter-update-2-1-25/4853

[VEN-3047]: increase supply cap of SolvBTC

---

simulations/vip-444/abi/CoreComptroller.json
simulations/vip-444/bscmainnet.ts
vips/vip-444/bscmainnet.ts

Resolves VEN-3052
https://community.venus.io/t/chaos-labs-risk-parameter-update-2-5-25/4863

[VEN-3051]: increase borrow and supply caps of THE

---

simulations/vip-446/abi/CoreComptroller.json
simulations/vip-446/bscmainnet.ts
vips/vip-446/bscmainnet.ts

[VEN-3057]: increase supply and borrow caps for THE

---

simulations/vip-449/abi/VTreasury.json
simulations/vip-449/abi/erc20.json
simulations/vip-449/bscmainnet.ts
vips/vip-449/bscmainnet.ts

[VEN-3027]: refund bootstrap liquidity providers for Unichain

---

multisig/proposals/unichainmainnet/vip-006/index.ts
multisig/simulations/unichainmainnet/vip-006/abi/ERC20.json
multisig/simulations/unichainmainnet/vip-006/abi/Prime.json
multisig/simulations/unichainmainnet/vip-006/abi/PrimeLiquidityProvider.json
multisig/simulations/unichainmainnet/vip-006/abi/XVS.json
multisig/simulations/unichainmainnet/vip-006/abi/XVSVault.json
multisig/simulations/unichainmainnet/vip-006/abi/comptroller.json
multisig/simulations/unichainmainnet/vip-006/index.ts

[ven-3067]: Prime on Unichain

---

multisig/proposals/unichainsepolia/vip-006/index.ts
multisig/simulations/unichainsepolia/vip-006/abi/Comptroller.json
multisig/simulations/unichainsepolia/vip-006/abi/Prime.json
multisig/simulations/unichainsepolia/vip-006/abi/PrimeLiquidityProvider.json
multisig/simulations/unichainsepolia/vip-006/abi/XVS.json
multisig/simulations/unichainsepolia/vip-006/abi/XVSVault.json
multisig/simulations/unichainsepolia/vip-006/index.ts

Resolves VEN-2915
Replace https://github.com/VenusProtocol/vips/pull/483

[VEN-2915]: Prime configuration on unichainsepolia

---

multisig/proposals/unichainmainnet/vip-007/index.ts
multisig/simulations/unichainmainnet/vip-007/abi/Comptroller.json
multisig/simulations/unichainmainnet/vip-007/index.ts
simulations/vip-453/abi/OmnichainProposalSender.json
simulations/vip-453/abi/comptroller.json
simulations/vip-453/bscmainnet.ts
simulations/vip-453/ethereum.ts
vips/vip-453/bscmainnet.ts

[VEN-3081]: add VIP following Chaos labs recommendations

---

simulations/vip-455/abi/OmnichainProposalSender.json
simulations/vip-455/abi/comptroller.json
simulations/vip-455/bscmainnet.ts
simulations/vip-455/ethereum.ts
vips/vip-455/bscmainnet.ts

Resolves VEN-3096
https://community.venus.io/t/chaos-labs-risk-parameter-update-2-19-25/4945

[VEN-3096]: increase some caps following Chaos Labs recommendations

---

simulations/vip-458/abi/OmnichainProposalSender.json
simulations/vip-458/abi/comptroller.json
simulations/vip-458/bscmainnet.ts
simulations/vip-458/ethereum.ts
vips/vip-458/bscmainnet.ts

Resolves VEN-3114
https://community.venus.io/t/chaos-labs-risk-parameter-update-2-25-25/4956

[VEN-3114]: add Chaos Labs recommendations

---

simulations/vip-459/abi/ERC20.json
simulations/vip-459/abi/OmnichainProposalSender.json
simulations/vip-459/abi/comptroller.json
simulations/vip-459/bscmainnet.ts
simulations/vip-459/ethereum.ts
vips/vip-459/bscmainnet.ts

Resolves VEN-3117
https://community.venus.io/t/chaos-labs-risk-parameter-updates-02-28-25

[VEN-3117]: increase BAL supply cap

---

simulations/vip-463/abi/OmnichainProposalSender.json
simulations/vip-463/abi/comptroller.json
simulations/vip-463/bscmainnet.ts
simulations/vip-463/unichainmainnet.ts
vips/vip-463/bscmainnet.ts

Resolves VEN-3126
https://community.venus.io/t/chaos-labs-risk-parameter-updates-03-06-25/4984

[VEN-3126]: increase caps following Chaos Labs recommendations

---

simulations/vip-465/abi/OmnichainProposalSender.json
simulations/vip-465/abi/comptroller.json
simulations/vip-465/bscmainnet.ts
simulations/vip-465/unichainmainnet.ts
vips/vip-465/bscmainnet.ts

Resolves VEN-3133
https://community.venus.io/t/chaos-labs-risk-parameter-updates-03-10-25/4986

[VEN-3133]: increase caps for USDC on Unichain - Chaos labs recommendations

---

simulations/vip-469/abi/PoolRegistry.json
simulations/vip-469/abi/ResilientOracle.json
simulations/vip-469/abi/SingleTokenConverter.json
simulations/vip-469/abi/comptroller.json
simulations/vip-469/abi/vToken.json
simulations/vip-469/bscmainnet.ts
simulations/vip-469/bsctestnet.ts
vips/vip-469/bscmainnet.ts
vips/vip-469/bsctestnet.ts

[VEN-3131]: asBNB market

---

simulations/vip-454/abi/ERC20.json
simulations/vip-454/abi/VTreasury.json
simulations/vip-454/bscmainnet.ts
vips/vip-454/bscmainnet.ts

Resolves VEN-3085
https://community.venus.io/t/coverage-for-vanguard-stars-social-engineering-incident-lossage/4896

[VEN-3085]: VIP for Coverage for Vanguard/Stars Social Engineering Incident Lossage

---

simulations/vip-474/abi/ERC20.json
simulations/vip-474/abi/VTreasury.json
simulations/vip-474/bscmainnet.ts
vips/vip-474/bscmainnet.ts

[VEN-3167]: VIP for payments

---

simulations/vip-478/abi/OmnichainProposalSender.json
simulations/vip-478/abi/SetterFacet.json
simulations/vip-478/abi/ilComptroller.json
simulations/vip-478/bscmainnet.ts
simulations/vip-478/ethereum.ts
vips/vip-478/bscmainnet.ts

https://community.venus.io/t/fdusd-depeg-response/5019/4
Resolves VEN-3180

[VEN-3180]: resume FDUSD and TUSD on BNB Chain and Ethereum

---

simulations/vip-479/abi/VTokenCorePool.json
simulations/vip-479/bscmainnet.ts
simulations/vip-479/bsctestnet.ts
vips/vip-479/bscmainnet.ts
vips/vip-479/bsctestnet.ts

https://community.venus.io/t/chaos-labs-bnb-ir-curve-update/5037
Resolves VEN-3182

[VEN-3182]: 2-kinks for vBNB with lower base rate in the 2nd slope

---

simulations/vip-484/abi/VTokenCorePool.json
simulations/vip-484/bscmainnet.ts
simulations/vip-484/bsctestnet.ts
simulations/vip-484/bsctestnet2.ts
vips/vip-484/bscmainnet.ts
vips/vip-484/bsctestnet.ts
vips/vip-484/bsctestnet2.ts

[VEN-3192]: risk parameters on vBNB following Chaos Labs recommendations

---

simulations/vip-488/abi/OmnichainProposalSender.json
simulations/vip-488/abi/comptroller.json
simulations/vip-488/bscmainnet.ts
simulations/vip-488/unichainmainnet.ts
vips/vip-488/bscmainnet.ts

[VEN-3208]: add VIP 488, following Chaos Labs recommendations

---

simulations/vip-490/abi/coreComptroller.json
simulations/vip-490/abi/ilComptroller.json
simulations/vip-490/bscmainnet.ts
vips/vip-490/bscmainnet.ts

Resolves VEN-3212
https://community.venus.io/t/chaos-labs-risk-parameter-updates-04-28-25/5078

[VEN-3212]: update caps following Chaos Labs recommendations

---

simulations/vip-496/abi/OmnichainProposalSender.json
simulations/vip-496/abi/comptroller.json
simulations/vip-496/abi/vToken.json
simulations/vip-496/bscmainnet.ts
simulations/vip-496/unichainmainnet.ts
vips/vip-496/bscmainnet.ts

Resolves VEN-3229
https://community.venus.io/t/unichain-increase-caps-for-usdc/5093/2

[VEN-3229]: increase USDC/Unichain caps following Chaos recs

---

simulations/vip-512/abi/OmnichainProposalSender.json
simulations/vip-512/abi/erc20.json
simulations/vip-512/abi/ilComptroller.json
simulations/vip-512/abi/resilientOracle.json
simulations/vip-512/abi/vToken.json
simulations/vip-512/bscmainnet.ts
simulations/vip-512/ethereum.ts
vips/vip-512/bscmainnet.ts

[VEN-3246]: add VIP 512 to add tBTC on Ethereum

---

simulations/vip-525/abi/coreComptroller.json
simulations/vip-525/bscmainnet.ts
vips/vip-525/bscmainnet.ts

Resolves VEN-3302
https://community.venus.io/t/chaos-labs-risk-parameter-updates-06-27-25/5179

[VEN-3302]: add VIP to increase supply caps of asBNB and xSolvBTC

---

simulations/vip-538/abi/coreComptroller.json
simulations/vip-538/bscmainnet.ts
vips/vip-538/bscmainnet.ts

Resolves VEN-3365
https://community.venus.io/t/chaos-labs-risk-parameter-updates-8-8-25/5271

[VEN-3365] VIP to increase supply cap of xSolvBTC and SolvBTC

---

simulations/vip-549/abi/vToken.json
simulations/vip-549/bscmainnet.ts
vips/vip-549/bscmainnet.ts

[VPD-164] Chaos labs recommendations (September 29th, 2025)
